### PR TITLE
Have ffe-icon resolve the path of --opt relative to current working directory

### PR DESCRIPTION
**Pull request by kwltrs**
Breaking changes in ffe-icons: The path passed to `--opt` is treated as relative to the current working directory, determined by `process.cwd()`.

### CODE REVIEW

**Review by wkillerud — DISMISSED** [review]
Nice! I'd love it if the commit message contained a diff example of how to migrate. Either that or link specifically to this PR so people can see a before/after example.

**Comment by wkillerud** [comment]
If you rebase from `master` the CI should be stable now (after #75)

**Comment by kwltrs** [comment]
The child commit b29ee89 is a good example on how to apply this change. But I'm not sure how and where to refer to that commit.

**Review by selbekk — DISMISSED** [review]
Not sure what is going on in most of this file, but I couldn't spot any major fups.

**Comment by wkillerud** [comment]
Still unstable? Darn it :rage: Allright, let's just lint things in sequence. I can make a PR.
Changes LGTM :)

Regarding referecing a single commit, it looks like Github can see that b29ee89 is a commit hash and fixes a link automagically :sparkles: So just write something like

```
See b29ee89 for an example on how to migrate
```

should work in theory.

**Comment by kwltrs** [comment]
When rewriting the commit with the fix, the following commit, that contains the migration, gets a new hash and the hash link is wrong. I reordered the commits so that the migration is before the fix.

**Review by wkillerud — APPROVED** [review]

**Pull request merged**
