### PR TITLE
Remove deprecated components

### PR DESCRIPTION
**Pull request by ivarni**

### CODE REVIEW

**Comment by kwltrs** [comment]
Can you explain why the react implementation is removed while the less is still around? Why not remove both in one breaking change?

**Comment by ivarni** [comment]
Because I suspect not many people are using the react components (they're quite new) while I know several teams are using the less code (it's quite old).

People who are using this layout can keep doing it with their own React-wrappers and still postpone the move to grid while we at least not enourage it to spread further by having these wrappers in here. If we remove the less code then people are going to be stuck on the current core major for a long time. I feel that's a much bigger leap to take right now.

**Comment by ivarni** [comment]
This relates to #149 btw

**Review by wkillerud — APPROVED** [review]

**Review by selbekk — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
