### PR TITLE
feat(ffe-context-message-react): ContextMessage components now pass r…

### PR DESCRIPTION
**Pull request by ivarni**
…est props onto root node

### CODE REVIEW

**Comment by henrikhermansen** [comment]
I'd like to suggest changing the commit message. Of course that long scope doesn't make it easy, but how about this?
> feat(ffe-context-message-react): pass rest props to root node
>
> ContextMessage components now pass rest props onto root node.

**Comment by ivarni** [comment]
@henrikhermansen Sure. Not sure it makes the changelog any more readable but I'd kinda just want this merged so I've updated the commit message :)

**Review by hdaljord — CHANGES_REQUESTED** [review]
Can you please add `extends React.HTMLAttributes<HTMLDivElement>` i index.d.ts for ContextMessageProps, to make this work for typescript users as well.

Like this:
`export interface ContextMessageProps extends React.HTMLAttributes<HTMLDivElement>{
`

**Comment by ivarni** [comment]
@hdaljord 

Done. I've no way of testing if it works though :)
~~Shittier~~ Prettier decided to automatically add a linebreak there but I assume that doesn't matter.

**Comment by hdaljord** [comment]
Nice, I've tested it locally :)

**Review by hdaljord — APPROVED** [review]

**Pull request merged**
