### PR TITLE
fix(ffe-core): Fix build issue

### LINKED ISSUE #299: ffe-core doesn't export ES5
#### Which package is this issue related to?
ffe-core

#### Describe your issue (screenshots welcome!)
When we build ffe-core, it creates some javascript files for variables, which can be imported. Unfortunately, the index file contains a trailing comma for functions, which are not ES5.

This leads to the build process failing whenever you use tools such as `create-react-app`.

### PR DESCRIPTION
**Pull request by selbekk**
This commit fixes an issue where using the JS variables from ffe-core
broke certain builds (in my case, create-react-app). The reason for the
breakage was a trailing comma in a function argument list, which is an
ES6 feature.

This commit removes the trailing comma, and makes the code slightly
easier to read.

Fixes #299

### CODE REVIEW

**Comment by ivarni** [comment]
I'd much rather see an actual transpile step, or at the very least a big hard-to-miss warning informing the next person of the need to keep the source completely in ES5. Everything else in FFE is written in ES6 so it's not very intuitive that this can't be.

**Comment by wkillerud** [comment]
Ivars suggestion seems more future-proof. This looks OK for now as a quick fix.

**Review by wkillerud — DISMISSED** [review]

**Comment by selbekk** [comment]
Hm.. well, sure, I don't mind adding a transpilation step further down the line.

**Comment by ivarni** [comment]
I don't think this closes the issue but it certainly works as a quickfix. I think leaving the issue open is a good idea so this doesn't re-appear as an issue again later if someone accidentally use new syntax.

**Comment by selbekk** [comment]
I added the babel build step. Good to go?

**Review by ivarni — APPROVED** [review]

**Pull request merged**
