### PR TITLE
Fix to make the project build on Windows

### PR DESCRIPTION
**Pull request by lotorvik**
Fixes problem in issue #411

This is not tested on linux, but Travis should test that for us.

### CODE REVIEW

**Review by ivarni — DISMISSED** [review]

**Comment by antidecaf** [comment]
Thanks for the PR, looks good to me!

Just a minor detail: 
Commit messages should contain the relevant package name when applicable, to ensure changelogs are generated correctly. (See [CONTRIBUTING.md](https://github.com/SpareBank1/designsystem/blob/develop/CONTRIBUTING.md#commit-meldinger)). The commit message in the autocomplete commit should read something like `fix(ffe-searchable-dropdown-react): ...`, if you don't mind changing it. :)

**Comment by ivarni** [comment]
Do we need a release and changelog for this though? 🤔

**Comment by antidecaf** [comment]
Any reason not to include the change in the changelog?

**Comment by ivarni** [comment]
Oh right.. the autocomplete stuff is in here as well... ignore me 🤡

**Comment by lotorvik** [comment]
I have now updated the comit message for the autocomplete, i looks correct in my editor with git commit --amend, but I see the () is stripped from fix(ffe-searchable-dropdown-react) here on github. Any suggestions?

**Comment by kwltrs** [comment]
@lotorvik did you use `--force` when pushing?

**Comment by lotorvik** [comment]
@kwltrs that seems to have done the trick, thanks

**Review by kwltrs — APPROVED** [review]

**Review by antidecaf — APPROVED** [review]

**Pull request merged**
