### PR TITLE
fix(ffe-webfonts): Make is possible for frontend apps that use sb1-st…

### PR DESCRIPTION
**Pull request by nordstrand**
…atic-resources to get font files copied

### CODE REVIEW

**Comment by wkillerud** [comment]
I see we can remove the field from `@sb1/ffe-core` now too. Would you mind removing it in a separate commit in this PR @nordstrand? :slightly_smiling_face:

**Comment by kwltrs** [comment]
I feel like having a talk if we want to support the proprietary build system using this entry.

**Comment by nordstrand** [comment]
Japp då har jag tagit bort detta från ffe-core @wkillerud  .

**Comment by nordstrand** [comment]
@kwltrs  jag sitter hær i 2. etagen om du vill snacka?

**Comment by kwltrs** [comment]
We came up with a better solution, which is not include here on github. Look up `sb1-webfonts-resources` in your local bitbucket.

**Pull request closed without merging**
