### PR TITLE
492 merge checkbox radio form

### PR DESCRIPTION
**Pull request by ivarni**

### CODE REVIEW

**Review by selbekk — DISMISSED** [review]
Great job!

Should the packages be removed from [`greenkeeper.json`](https://github.com/SpareBank1/designsystem/blob/develop/greenkeeper.json) and  [`commitlint.config.js`](https://github.com/SpareBank1/designsystem/blob/develop/commitlint.config.js) also?

**Comment by ivarni** [comment]
I suppose removing them from greenkeeper is a good idea, dunno about commitlint untill we remove them completely?

**Comment by ivarni** [comment]
Hot damn, of course `ffe-account-selector-react` is now failing because of the removed modules, it seems I can't really do the merge in the same PR as I remove the old code, which I suppose makes sense.

**Review by selbekk — APPROVED** [review]
ah right. Yep, this makes sense.

**Comment by ivarni** [comment]
Ninja-merger med en approval fordi #531 ikke kan fikses ferdig-ferdig før dette er published.

**Pull request merged**
