### PR TITLE
feat(ffe-searchable-dropdown-react): added darkmode styling

### PR DESCRIPTION
**Pull request by mvmagnussen**
Added darkmode styling to searchable dropdown list. 

image

Note that this PR does not solve the styling issues described in #815.

### CODE REVIEW

**Review by pethel — DISMISSED** [review]
Only issue I saw was that you need repeat the styling, but if thats not fixable this is ok for me.
```
.ffe-searchable-dropdown__list {
        background: @ffe-grey-dark-blue--dark;	       
        .native & {
            @media (prefers-color-scheme: dark) {
                background: @ffe-grey-dark-blue--dark;
            }
        }
    }	
```

**Comment by mvmagnussen** [comment]
> Only issue I saw was that you need repeat the styling, but if thats not fixable this is ok for me.
> 
> ```
> .ffe-searchable-dropdown__list {
>         background: @ffe-grey-dark-blue--dark;	       
>         .native & {
>             @media (prefers-color-scheme: dark) {
>                 background: @ffe-grey-dark-blue--dark;
>             }
>         }
>     }	
> ```

I know it looks redundant, but I have to do this, or else the styling will be overwritten by the dark mode styling when in dark mode :/

**Review by pethel — APPROVED** [review]

**Comment by pethel** [comment]
Husk og squash commitesen bare.

**Comment by mvmagnussen** [comment]
Closing and opening a new PR to clean up commits.

**Pull request closed without merging**
