### PR TITLE
Spacing and typo adjustments

### PR DESCRIPTION
**Pull request by antidecaf**
* Added new variables for standardized spacing
* Adjusted typography according to new values in the Figma master file

### CODE REVIEW

**Comment by ivarni** [comment]
If we're introducing a whole new system for spacing, doesn't that justify a new major version? 
Font-size changes, especially increases, has a non-zero chance of breaking existing layout.

Some instructions on how to use these variables and general information about the new spacing system would also be a very nice thing.

**Comment by antidecaf** [comment]
> Font-size changes, especially increases, has a non-zero chance of breaking existing layout.

Yeah, agreed. I'll rewrite that commit message to include breaking change.

> If we're introducing a whole new system for spacing, doesn't that justify a new major version?

> Some instructions on how to use these variables and general information about the new spacing system would also be a very nice thing.

I've only added the variables for now in order make them available in different apps, will document and implement them in the design system components in a later PR.

**Comment by ivarni** [comment]
Sounds good. Looking forward to when this is all in place. We have a lot of inconsistent spacing around.

**Comment by antidecaf** [comment]
Indeed we do. And that makes the upcoming PR a bit painful. :sob:

**Review by ivarni — APPROVED** [review]

**Pull request merged**
