### PR TITLE
fix(ffe-buttons-react): invalid markup

### PR DESCRIPTION
**Pull request by pethel**
A button tag must have phrasing content children.

### CODE REVIEW

**Review by henrikhermansen — APPROVED** [review]
LGTM given you've checked for visual regressions.

**Comment by pethel** [comment]
Still looks good.. 
image

https://files.slack.com/files-pri/TN04X3213-FP3HNS1A7/image.png
image

**Comment by ivarni** [comment]
What exactly was invalid about this markup?

**Comment by ivarni** [comment]
Oh right, child content rules. I wouldn't mind if that was in the changelog (I know I'm sounding like a broken record here but I often check the changelog before updating and it's a lot of extra work hunting down the commits compared to just writing what's fixed in the commit message).

**Comment by pethel** [comment]
@ivarni, this is the commit message. It will end up in the change log? Is not clear enough?

```
fix(ffe-buttons-react): invalid markup

button tag must have phrasing content child elements.
```

**Comment by ivarni** [comment]
@pethel Ah, no that's good, I was fooled by the github UI then :)

image

**Pull request merged**
