### PR TITLE
fix(ffe-accordion): change the rotation axis for the accordian chevron animation.

### PR DESCRIPTION
**Pull request by benmatthews**

### CODE REVIEW

**Review by selbekk — COMMENTED** [review]
I think the current implementation is nicer to look at to be honest. Where is this change coming from?

This is the current behavior: 
https://design.sparebank1.no/styleguidist/index.html#!/Accordion

**Comment by benmatthews** [comment]
This change is coming from this [issue 180](https://github.com/SpareBank1/designsystem/issues/180) and there is a section in the design guide on [bevegelse i X- og Y-asken](https://design.sparebank1.no/visuell-identitet.html#visuell-identitet_animasjoner).  Maybe the correct solution is to remove the animation?

**Comment by selbekk** [comment]
Aha! I think the current approach look good, but if there are arguments that we shouldn't animate stuff across the Z-axis, that's fine by me.

**Comment by benmatthews** [comment]
Well, the alternative is to just not animate the transition... I can check with Adi.

**Review by wkillerud — APPROVED** [review]
LGTM

**Review by wkillerud — APPROVED** [review]
LGTM

**Pull request merged**
