### PR TITLE
Minor styleguide bugfixes

### PR DESCRIPTION
**Pull request by antidecaf**
* Fixes a few typos
* Adds missing viewport meta tag

### CODE REVIEW

**Comment by selbekk** [comment]
Have you done a global search for `SpareBank 1s` in the code base? Might as well replace them all, and I think there might have been one or two more that I didn't bother commenting on.

**Comment by antidecaf** [comment]
@selbekk I have made sure all instances are correct within `/styleguide-content`. Searching for that term in the rest of the repo will return loads of hits and very few relevant ones, though. :)

**Comment by antidecaf** [comment]
@selbekk Oops, disregard that. I had searched for `SpareBank1` vs `SpareBank 1` as opposed to `SpareBank 1s`. Update incoming.

**Review by wkillerud — APPROVED** [review]

**Review by selbekk — APPROVED** [review]
Great job bud!

**Pull request merged**
